### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by sbcgua** [abapGit-tests/PROG#1]
Hi @larshp 
Would like to add translation to the test. A couple of questions
1) should I commit directly or via PR as in AG ?
2) should I commit to this one or create a new repo ? I'm going to implement translation for screens and gui statuses in a while so ... shoull I keep this repo as a minimal working one and add a new one, more complex ? (imho, I'd adjust this one)
3) what will happen when I adjust this repo ? :) Seems that I completely missed this topic with the automatic tests of AG in the discussions. Is it becomes visible somewhere that it does not pass ? I've seen some jenkins screenshots passing by in slack ...

**Comment by larshp** [comment]
1. in the abapGit-tests organization feel free to commit directly or via PR, typically its a new test, so nothing will be overwritten so a new commit is the easiest
2. new repository, more test cases makes it eaiser to figure out what is wrong. Keep this one as is, add a "PROG_screen_translated" a "PROG_dynpro_translated" a combination of both etc. or just one new repo. Its nice to have the minimal examples
3. it shows up on https://ci.abapgit.org when Christian updates it

**Comment by larshp** [comment]
Regarding translations, in general we have some open issues in abapGit regarding this. If you open an issue for what you are working on I'll link it. We need to consider the approach.

**Comment by sbcgua** [comment]
Thanks !
P.S. Approach ... yeah ... I also have an idea about the approach, but when I though how to implement it I ended up with "complete rewrite needed" :) As usual :) And I really would like to have those screens and statuses soon ... well, will try to get my hands on it this week anyway

**Comment by sbcgua** [comment]
And this one can be closed then, thanks for the clarification again :)

**Comment by larshp** [comment]
If you open an issue in abapGit for translating screens and status'es, I'll add a few thoughts and link there, dont want to link from here(to avoid too much spam)
